apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  namespace: microservices-demo
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5000"
  ReverseProxy__Clusters__userservice__Destinations__destination1__Address: "http://userservice-service:5001"
  ReverseProxy__Clusters__productservice__Destinations__destination1__Address: "http://productservice-service:5002"
