apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
  namespace: microservices-demo
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5001"
  App__BaseUrl: "http://localhost:30000"
  Email__SmtpHost: "smtp.gmail.com"
  Email__SmtpPort: "587"
  Email__FromName: "Microservices Demo"
